### ISSUE TITLE
Library doesn't exist

### ISSUE THREAD

**Issue by lopste** [JSInventions/roostjs#1]
I can't use the library, the only things in the repository are a LISCENSE and a readme. Hope this helps!

**Comment by WojtekCodesToday** [comment]
I'm working very hard, and that's the reason.

**Comment by WojtekCodesToday** [comment]
You can use the [Gist](https://gist.github.com/WojtekCodesToday/7d7aa6fb21c0acae76cb0e0021cfac1e) that is available.

**Comment by WojtekCodesToday** [comment]
@lopste, done.
